# Generated by Django 5.0.2 on 2025-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0002_alter_document_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_contact',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='client_mail',
            field=models.EmailField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='project_location',
            field=models.TextField(default='N/A', max_length=60),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='sender_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(default='N/A', max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('not_started', 'Not Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=100),
        ),
    ]
