# Generated by Django 5.0.2 on 2025-02-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0003_project_client_contact_project_client_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_contact',
            field=models.CharField(default='+91', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_mail',
            field=models.EmailField(default='@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('not_started', 'Not Started'), ('completed', 'Completed')], default='active', max_length=15),
        ),
    ]
